/**
 * Writes convex/betterAuth/schema.ts from the Better Auth options in convex/auth.ts.
 *
 *   pnpm auth:schema
 *
 * Run it after changing Better Auth plugins or upgrading better-auth. convex/betterAuth/schema.test.ts fails while the
 * committed schema is out of date. The index rules follow @convex-dev/better-auth's own generator.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getAuthTables } from 'better-auth/db';
import { createAuthOptions } from '../convex/auth';

const OUTPUT = join(import.meta.dirname, '..', 'convex', 'betterAuth', 'schema.ts');

// Indexes the component's adapter queries by, in addition to unique and reference fields.
const MANUAL_INDEXES: Record<string, (string | string[])[]> = {
  account: ['accountId', ['accountId', 'providerId'], ['providerId', 'userId']],
  rateLimit: ['key'],
  session: ['expiresAt', ['expiresAt', 'userId']],
  verification: ['expiresAt', 'identifier'],
  user: [['email', 'name'], 'name', 'userId'],
};

const TYPES: Record<string, string> = {
  string: 'v.string()',
  boolean: 'v.boolean()',
  number: 'v.number()',
  date: 'v.number()',
  json: 'v.string()',
  'number[]': 'v.array(v.number())',
  'string[]': 'v.array(v.string())',
};

const tables = getAuthTables(createAuthOptions({} as never));
let code = `// Generated by scripts/generate-auth-schema.ts from convex/auth.ts. Do not edit; run \`pnpm auth:schema\`.

import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export const tables = {
`;

for (const [key, table] of Object.entries(tables)) {
  const fields = Object.entries(table.fields).filter(([name]) => name !== 'id');
  const fieldName = (name: string) => table.fields[name]?.fieldName ?? name;

  const lines = fields.map(([name, attr]) => {
    const type = TYPES[attr.type as string];
    if (!type) throw new Error(`Unsupported Better Auth field type ${String(attr.type)} on ${key}.${name}`);
    return `    ${attr.fieldName ?? name}: ${attr.required ? type : `v.optional(v.union(v.null(), ${type}))`},`;
  });

  const manual = (MANUAL_INDEXES[key] ?? []).map((index) =>
    typeof index === 'string' ? [fieldName(index)] : index.map(fieldName),
  );
  const special = fields
    .filter(([, attr]) => attr.unique || attr.sortable || attr.references)
    .map(([name, attr]) => attr.fieldName ?? name)
    .filter((name) => !manual.some((index) => index[0] === name))
    .map((name) => [name]);
  const indexes = [...manual, ...special].map((index) => {
    const sorted = [...index].sort();
    return `.index('${sorted.join('_')}', ${JSON.stringify(sorted).replaceAll('"', "'")})`;
  });

  code += `  ${table.modelName}: defineTable({\n${lines.join('\n')}\n  })${indexes.map((index) => `\n    ${index}`).join('')},\n`;
}

code += `};

export default defineSchema(tables);
`;

writeFileSync(OUTPUT, code);
console.warn(`Wrote ${OUTPUT}`);
